branches:
  only:
    - master

build: false

platform:
  - x64
  #- x86

image:
  - Visual Studio 2017
  - Visual Studio 2015

environment:
  matrix:
    - MINICONDA: C:\fastscapelib-conda

init:
  - "ECHO %MINICONDA%"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCARGUMENT=%PLATFORM%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" if "%PLATFORM%" == "x64" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  #- if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" if "%PLATFORM%" == "x86" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - echo "%VCVARPATH% %VCARGUMENT%"
  - "%VCVARPATH% %VCARGUMENT%"
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\fastscapelib-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install gtest cmake xtensor -c conda-forge
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" conda install xtensor-python pybind11 numpy pytest -c conda-forge
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -D CMAKE_INSTALL_PREFIX=%MINICONDA%\\LIBRARY -DBUILD_TESTS=ON -DDISABLE_VS2017=ON -DCMAKE_BUILD_TYPE=Release ..
  - nmake test_fastscapelib
  - "set PYTHONHOME=%MINICONDA%"
  - cd ..\\python
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" pip install -e . -v
  - cd ..

build_script:
  - cd build\\test
  - .\test_fastscapelib
  - cd ..\\..\\python
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" pytest fastscapelib -vv
