trigger:
  - main

pr:
  - main

jobs:
  - template: ./.azure-pipelines/azure-pipelines-linux-gcc.yml
  - template: ./.azure-pipelines/azure-pipelines-macos.yml
  - template: ./.azure-pipelines/azure-pipelines-win.yml
  - template: ./.azure-pipelines/azure-pipelines-linux-python.yml
  - template: ./.azure-pipelines/azure-pipelines-macos-python.yml
  - template: ./.azure-pipelines/azure-pipelines-win-python.yml
