steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda create -n fastscapelib python=$(python_version) cmake xtensor-python pytest pip -c conda-forge
      source activate fastscapelib
    displayName: Install dependencies

  - script: |
      source activate fastscapelib
      python -m pip install -e -v .
    displayName: Build and install fastscapelib Python bindings
    workingDirectory: $(Build.SourcesDirectory)/python

  - script: |
      source activate fastscapelib
      pytest .
    displayName: Test fastscapelib python bindings
    workingDirectory: $(Build.SourcesDirectory)/python/fastscapelib/tests
