steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda create -n fastscapelib gtest cmake xtensor -c conda-forge
      source activate fastscapelib
    displayName: Install dependencies

  - script: |
      source activate fastscapelib
      mkdir build
      cd build
      cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX $CMAKE_EXTRA_ARGS -DDOWNLOAD_GTEST=ON $(Build.SourcesDirectory)
    displayName: Configure fastscapelib
    workingDirectory: $(Build.BinariesDirectory)

  - script: |
      source activate fastscapelib
      make -j2
    displayName: Build fastscapelib
    workingDirectory: $(Build.BinariesDirectory)/build

  - script: |
      source activate fastscapelib
      cd test
      cmake --build . -- test
    displayName: Test fastscapelib
    workingDirectory: $(Build.BinariesDirectory)/build/test
